### ISSUE TITLE
STC node mining & STC mining pool

### ISSUE THREAD

**Issue by ren-ryder** [starcoinorg/sips#21]
Preface: I am applying for a grant based off a recommendation from Jolestar. 
___________
Starcoin is a next generation decentralized blockchain, and I believe it will see much success in the coming years. However, as a miner with 12 ST boxes running in my home, I do find there are potential issues with regards to centralization and distribution of hashpower to a very small number of mining pools, and to DXPOOL especially, which dominates the space despite high reject rates. 

Within the STC community, we feel that there are limited choices for mining pools, which, by their nature, are centralized. In addition to the obvious centralization component of a small number of mining pools, there are high reject rates, fees & latencies, plus not very consistent uptime due to server locations. A small group of us brought this problem to Tim Yang and Jolestar, and they agreed that this scenario creates a definite problem, Tim noted especially that there is no way to communicate with these centralized pools. 

Be that as it may, the Starcoin devs are hard at work on many projects, and while Jolestar sees the merit in this project, he has no bandwidth to pursue the matter. Jolestar recommended the community take on the project, and so I put a small group together of individuals willing to work on trying to figure out the specific requirements of building a node mining solution for STC.

This is where I fully began to comprehend the complexity of the issue itself, and the kind of specialized skillset that would be required to complete such a project. Seeing as the tech experts in our group could comprehend, but not execute, this project, I sought out a way to acquire a developer with this specific skillset. 

To date, I have engaged a dev team, a small team that has created and is running a similar project in the kda ecosystem @cmpool. They looked into the feasibility of whether or not they could handle the task, and verified they are fully capable of solving this issue. Although they are rebuilding their stratum as we speak and optimizing their own product, they are willing to put this project on the calendar, especially in the case that I can secure funding for their lead developer. I was quoted at 10-15K USD, which would amount to 100,000-150,000 STC for the production of this node mining solution. 

I think this project has much merit for the STC community, especially as the blockchain grows and expands, and more miners come online. An individually deployable node mining solution paired with either a community-ran pool, or a Starcoin Official pool, further decentralize the project by enabling miners to remove their hashpower from the pool and mine to their own node, or join small, stc-approved mining pools created under the foundation's direction. 

I will happily provide this node mining solution to Starcoin and its community for its free use, whether that be via the creation of a Starcoin official pool, as well, of course, as a free disemnation of the code via github, permanently open source and available. I am not seeking to profit off this venture, but to benefit the STC community as a whole to the best of my ability and within my own time and life constraints.

Warmly,
~Ren

Contact info:
Telegram @renryder Twitter: @renryderauthor email: ren@renryder.com

**Comment by jolestar** [comment]
1. Can you describe the technology in more detail? Such as how does the pool distribute fees to miners? it is decentralized? or miner need to trust the pool owner?

2. Can you introduce the dev team in more detail? Such as their programming experience.

**Comment by ren-ryder** [comment]
Absolutely, and thanks for engaging.

I plan on putting together a roadmap alongside providing key metrics and data for the community to scrutinize and inform themselves with. 

So, this project has a two-prong approach: providing miners with a decentralized node mining solution that is entirely trustless ~ eg they will get paid out for their work without having to go through a pool. I do understand that certain individuals and community members might have difficulties with unpacking and running their own node, but I will ensure there are guides to make it as simple as seamless as possible. 

However, there are likely still people who will be unable to surmount the technical difficulties or don't have the infrastructure to run their own node, and that's where a community-ran mining pool becomes something that has merit. So, I think the best solution is to also develop and provide a community mining pool with very low fees, something that the dev team @CMPOOL is willing and able to provide. 

I will engage CMPOOL so that they can introduce themselves & provide technical details about mining fee distribution, and their prior experience here for review.
